# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.vm.box = "manager-for-lustre/centos73-1611-builder"

	# Hostname prefix and network information
	host_prefix="ct7"
	# The additional network is not strictly necessary but
	# leaves open the option to connect the VM to a network
	# of other VMs on the host.
	subnet_prefix="10.12"
	mgmt_net_pfx="#{subnet_prefix}.10"

	# Create a basic hosts file for the VMs.
	open('hosts', 'w') { |f|
	f.puts <<-__EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

#{mgmt_net_pfx}.9 #{host_prefix}-builder.lfs.local #{host_prefix}-builder
__EOF
	}
	config.vm.provision "shell", inline: "cp -f /vagrant/hosts /etc/hosts"

	# Create the build server
	config.vm.define "builder", primary: true do |b|
		b.vm.provider "virtualbox" do |v|
			v.memory = 4096
			v.cpus = 2
		end
		b.vm.host_name = "#{host_prefix}-builder.lfs.local"
		# Admin / management network
		b.vm.network "private_network",
			ip: "#{mgmt_net_pfx}.9",
			netmask: "255.255.255.0"
	end
end
